export const projectsData = [
  {
    id: "resumai",
    title: "ResumAI",
    description: "AI-powered resume builder that creates professional resumes and cover letters with intelligent suggestions, keyword optimization, and multiple export formats.",
    image: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg",
    categories: ["Professional", "AI Integration"],
    technologies: ["Next.js", "OpenRouter API", "Tailwind CSS", "TypeScript"],
    liveUrl: "https://resumai-ai.vercel.app/",
    githubUrl: "https://github.com/CodnanBaig/resumai-ai",
  },
  {
    id: "codebuddy",
    title: "CodeBuddy",
    description: "Pair programming assistant using Ollama to provide real-time code suggestions and refactoring.",
    image: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg",
    categories: ["AI Integration", "Developer Tool"],
    technologies: ["React", "Ollama API", "Monaco Editor", "TypeScript"],
    liveUrl: "https://codebuddy-demo.vercel.app",
    githubUrl: "https://github.com/username/codebuddy",
  },
  {
    id: "dataviz",
    title: "DataViz Dashboard",
    description: "Real-time data visualization platform with AI-powered insights and trend analysis.",
    image: "https://images.pexels.com/photos/669996/pexels-photo-669996.jpeg",
    categories: ["Work Projects", "Web App"],
    technologies: ["Next.js", "Recharts", "Framer Motion", "TensorFlow.js"],
    liveUrl: "https://dataviz-demo.vercel.app",
    githubUrl: "https://github.com/username/dataviz",
  },
  {
    id: "aiwriter",
    title: "AI Writer",
    description: "Content generation tool that helps create blog posts, marketing copy, and social media content.",
    image: "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    categories: ["AI Integration", "Web App"],
    technologies: ["React", "OpenAI API", "Express", "MongoDB"],
    liveUrl: "https://aiwriter-demo.vercel.app",
    githubUrl: "https://github.com/username/aiwriter",
  },
  {
    id: "smartinventory",
    title: "Smart Inventory",
    description: "Inventory management system with predictive ordering and AI-powered demand forecasting.",
    image: "https://images.pexels.com/photos/3888151/pexels-photo-3888151.jpeg",
    categories: ["Web App", "AI Integration"],
    technologies: ["Next.js", "Supabase", "TensorFlow.js", "Chart.js"],
    liveUrl: "https://smartinventory-demo.vercel.app",
    githubUrl: "https://github.com/username/smartinventory",
  },
  {
    id: "mobilecompanion",
    title: "Mobile Companion",
    description: "Cross-platform mobile app with AI assistant capabilities for productivity and organization.",
    image: "https://images.pexels.com/photos/193004/pexels-photo-193004.jpeg",
    categories: ["Mobile", "AI Integration"],
    technologies: ["React Native", "Expo", "Firebase", "Mistral AI"],
    liveUrl: "https://mobilecompanion-demo.vercel.app",
    githubUrl: "https://github.com/username/mobilecompanion",
  }
];