export const projectsData = [
  {
    id: "streck",
    title: "STRECK - Streetwear for the Unhinged",
    description: "Bold, chaotic, unapologetically desi streetwear e-commerce platform for Gen Z rebels. Features modern Next.js 14 frontend, responsive design, real-time cart management, product categories, GSAP animations, and full admin panel with CRUD operations.",
    image: "/screenshots/streck-banner.png",
    categories: ["Personal", "E-commerce", "Web App"],
    technologies: ["Next.js 14", "React 18", "TypeScript", "Tailwind CSS", "Radix UI", "GSAP", "Prisma", "SQLite", "Cloudinary", "React Context"],
    liveUrl: "https://streck.in",
    featured: true,
    detailedDescription: "STRECK is a bold and unapologetic streetwear e-commerce platform designed for Gen Z rebels who embrace chaos and reject conventional norms. Built with Next.js 14 and modern web technologies, it features a comprehensive shopping experience with real-time cart management, smooth GSAP animations, and a full admin panel. The platform offers curated collections including 18+ content, fitness gear, pet lovers merchandise, comedy items, and professional wear for rebels. The application demonstrates advanced e-commerce functionality with Cloudinary image optimization, Prisma ORM for database management, and responsive design that works seamlessly across all devices.",
    keyFeatures: [
      "Modern e-commerce store with Next.js 14 frontend",
      "Real-time cart management with localStorage persistence",
      "Organized product categories and collections",
      "Smooth GSAP animations for enhanced UX",
      "Full admin panel with CRUD operations",
      "Cloudinary integration for image optimization",
      "Responsive design for desktop and mobile",
      "TypeScript for full type safety"
    ],
    technicalHighlights: [
      "Next.js 14 with App Router and React 18",
      "Prisma ORM with SQLite database",
      "Cloudinary for image storage and optimization",
      "GSAP for smooth animations and transitions",
      "Radix UI components with Tailwind CSS",
      "React Context for state management",
      "Local storage for cart persistence",
      "Comprehensive admin panel functionality"
    ]
  },
  {
    id: "tunewave-dashboard",
    title: "Tunewave Media Dashboard",
    description: "Admin dashboard for media operations with authentication and analytics views.",
    image: "/screenshots/tunewave-dashboard-banner.png",
    categories: ["Professional", "Web App"],
    technologies: ["Next.js", "TypeScript", "Charts"],
    liveUrl: "https://dashboard.tunewavemedia.in",
    featured: true,
  },
  {
    id: "dont-go-broke-flutter",
    title: "Don't Go Broke (FuelWallet)",
    description: "A comprehensive Flutter app for tracking expenses, budgets, and financial insights. Built with Provider for state management, Supabase-ready services, and responsive UI using Sizer. Features expense tracking, budget management, financial insights, and SMS integration for automated expense categorization.",
    image: "https://images.pexels.com/photos/193004/pexels-photo-193004.jpeg",
    categories: ["Personal", "Mobile", "Finance"],
    technologies: ["Flutter", "Dart", "Provider", "Supabase", "Sizer", "Fl Chart", "Shared Preferences", "Dio"],
    githubUrl: "https://github.com/CodnanBaig/dont-go-broke-flutter",
    featured: true,
    detailedDescription: "Don't Go Broke is a sophisticated financial management app built with Flutter. The app provides comprehensive expense tracking, budget management, and financial insights. It features a clean, responsive UI built with Sizer for adaptive design, Provider for state management, and Supabase integration for backend services. Key features include expense categorization, budget creation and tracking, financial insights with charts, SMS integration for automated expense detection, and multi-platform support for iOS, Android, and web.",
    keyFeatures: [
      "Expense tracking and categorization",
      "Budget creation and management", 
      "Financial insights with interactive charts",
      "SMS integration for automated expense detection",
      "Responsive UI with Sizer for adaptive design",
      "Supabase backend integration",
      "Provider state management",
      "Multi-platform support (iOS, Android, Web)"
    ],
    technicalHighlights: [
      "Flutter SDK 3.6+ with Dart",
      "Provider pattern for state management",
      "Supabase for backend services and authentication",
      "Sizer for responsive design across devices",
      "Fl Chart for financial data visualization",
      "Dio for HTTP client and API communication",
      "Shared Preferences for local data persistence",
      "Comprehensive testing with Flutter Driver and Integration Tests"
    ]
  },
  {
    id: "resumai",
    title: "ResumAI",
    description: "A comprehensive Next.js 15 application for building, enhancing, and exporting professional resumes and cover letters. Features AI-powered content enhancement via OpenRouter, modern editable templates with rich text editing, PDF generation, and JWT-based authentication.",
    image: "/screenshots/resumai-banner.png",
    categories: ["Personal", "AI Integration", "Web App"],
    technologies: ["Next.js 15", "React 19", "TypeScript", "Prisma", "OpenRouter API", "Tailwind CSS", "Radix UI", "PDF-lib", "Playwright", "JWT", "bcryptjs"],
    liveUrl: "https://resumai-ai.vercel.app/",
    githubUrl: "https://github.com/CodnanBaig/resumai-ai",
    featured: true,
    detailedDescription: "ResumAI is a sophisticated resume and cover letter builder powered by AI. Built with Next.js 15 and React 19, it provides intelligent content enhancement, keyword optimization, and professional template management. The application features modern UI components with Radix UI, comprehensive PDF generation capabilities, and secure JWT-based authentication. Users can create, edit, and export professional documents with AI-powered suggestions and multiple format options.",
    keyFeatures: [
      "AI-powered resume enhancement via OpenRouter",
      "Cover letter generation tailored to job descriptions",
      "Modern editable resume templates with rich text editing",
      "PDF generation for resumes and cover letters",
      "Email/password authentication with JWT sessions",
      "SQLite development database with Prisma ORM",
      "Keyword optimization and ATS-friendly formatting",
      "Multiple export formats (PDF, DOCX)"
    ],
    technicalHighlights: [
      "Next.js 15 App Router with React 19",
      "TypeScript for type safety",
      "Prisma ORM with SQLite (dev) and MySQL (production)",
      "OpenRouter API integration for AI features",
      "JWT authentication with bcryptjs password hashing",
      "PDF generation using pdf-lib and Playwright",
      "Radix UI components with Tailwind CSS",
      "TipTap rich text editor for content creation"
    ]
  },
  {
    id: "codebuddy",
    title: "CodeBuddy",
    description: "Pair programming assistant using Ollama to provide real-time code suggestions and refactoring.",
    image: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg",
    categories: ["AI Integration", "Developer Tool"],
    technologies: ["React", "Ollama API", "Monaco Editor", "TypeScript"],
    liveUrl: "https://codebuddy-demo.vercel.app",
    githubUrl: "https://github.com/username/codebuddy",
  },
  {
    id: "dataviz",
    title: "DataViz Dashboard",
    description: "Real-time data visualization platform with AI-powered insights and trend analysis.",
    image: "https://images.pexels.com/photos/669996/pexels-photo-669996.jpeg",
    categories: ["Work Projects", "Web App"],
    technologies: ["Next.js", "Recharts", "Framer Motion", "TensorFlow.js"],
    liveUrl: "https://dataviz-demo.vercel.app",
    githubUrl: "https://github.com/username/dataviz",
  },
  {
    id: "aiwriter",
    title: "AI Writer",
    description: "Content generation tool that helps create blog posts, marketing copy, and social media content.",
    image: "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    categories: ["AI Integration", "Web App"],
    technologies: ["React", "OpenAI API", "Express", "MongoDB"],
    liveUrl: "https://aiwriter-demo.vercel.app",
    githubUrl: "https://github.com/username/aiwriter",
  },
  {
    id: "smartinventory",
    title: "Smart Inventory",
    description: "Inventory management system with predictive ordering and AI-powered demand forecasting.",
    image: "https://images.pexels.com/photos/3888151/pexels-photo-3888151.jpeg",
    categories: ["Web App", "AI Integration"],
    technologies: ["Next.js", "Supabase", "TensorFlow.js", "Chart.js"],
    liveUrl: "https://smartinventory-demo.vercel.app",
    githubUrl: "https://github.com/username/smartinventory",
  },
  {
    id: "mobilecompanion",
    title: "Mobile Companion",
    description: "Cross-platform mobile app with AI assistant capabilities for productivity and organization.",
    image: "https://images.pexels.com/photos/193004/pexels-photo-193004.jpeg",
    categories: ["Mobile", "AI Integration"],
    technologies: ["React Native", "Expo", "Firebase", "Mistral AI"],
    liveUrl: "https://mobilecompanion-demo.vercel.app",
    githubUrl: "https://github.com/username/mobilecompanion",
  }
  ,
  // Added personal GitHub repositories
  {
    id: "pitcheme",
    title: "PitchGenie",
    description: "AI-powered pitch deck and proposal generator built with Next.js 15. Features AI-assisted content generation, export to PDF/DOCX, Stripe billing integration, and comprehensive testing suite. Helps founders, sales teams, and consultants create compelling documents in minutes.",
    image: "/screenshots/pitcheme-banner.png",
    categories: ["Personal", "Web App", "AI Integration"],
    technologies: ["Next.js 15", "React 19", "TypeScript", "NextAuth", "Prisma", "Stripe", "AI SDK", "OpenAI", "Puppeteer", "Jest", "Tailwind CSS", "Radix UI"],
    liveUrl: "https://pitcheme.netlify.app/",
    githubUrl: "https://github.com/CodnanBaig/pitcheme",
    featured: true,
    detailedDescription: "PitchGenie is a comprehensive AI-powered platform for generating pitch decks and business proposals. Built with Next.js 15 and React 19, it combines modern web technologies with AI capabilities to help users create compelling business documents. The platform features secure authentication, AI-assisted content generation, professional document export capabilities, and integrated billing through Stripe. It's designed for founders, sales teams, and consultants who need to create high-quality presentations quickly.",
    keyFeatures: [
      "AI-assisted generation of pitch decks and proposals",
      "Export generated documents to PDF and DOCX formats",
      "Stripe integration for billing and customer portal",
      "Email/password authentication with NextAuth",
      "Modern UI built with Tailwind CSS and Radix UI",
      "Comprehensive testing suite with Jest",
      "Prisma ORM with SQLite database",
      "Puppeteer for document generation and export"
    ],
    technicalHighlights: [
      "Next.js 15 App Router with React 19",
      "NextAuth for authentication with Prisma adapter",
      "AI SDK with OpenAI provider for content generation",
      "Stripe integration for payments and subscriptions",
      "Prisma ORM with SQLite (dev) and configurable for production",
      "Puppeteer for PDF/DOCX document generation",
      "Comprehensive Jest testing (API, integration, performance, security)",
      "Radix UI primitives with Tailwind CSS styling"
    ]
  },
  {
    id: "muay-thai",
    title: "Nak Muay Trainer",
    description: "A comprehensive Muay Thai training companion app built with Expo and React Native. Features training routines, drills, timers, progress tracking, and audio guidance for Muay Thai practitioners. Built with modern React Native technologies and NativeWind for styling.",
    image: "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    categories: ["Personal", "Mobile", "Fitness"],
    technologies: ["React Native", "Expo", "TypeScript", "NativeWind", "React Navigation", "Expo Router", "Expo Audio", "React Native Reanimated", "AsyncStorage"],
    githubUrl: "https://github.com/CodnanBaig/muay-thai",
    featured: true,
    detailedDescription: "Nak Muay Trainer is a specialized mobile application designed for Muay Thai practitioners. Built with Expo and React Native, it provides comprehensive training tools including customizable routines, drill timers, progress tracking, and audio guidance. The app features a modern UI with NativeWind styling, smooth animations with React Native Reanimated, and cross-platform compatibility. It's designed to help fighters improve their training consistency and track their progress over time.",
    keyFeatures: [
      "Customizable training routines and drills",
      "Built-in timers for rounds and rest periods",
      "Progress tracking and analytics",
      "Audio guidance and haptic feedback",
      "Cross-platform support (iOS, Android, Web)",
      "Modern UI with NativeWind styling",
      "Smooth animations and transitions",
      "Offline functionality with AsyncStorage"
    ],
    technicalHighlights: [
      "Expo SDK 53 with React Native",
      "TypeScript for type safety",
      "NativeWind for Tailwind CSS styling",
      "Expo Router for file-based navigation",
      "React Navigation for complex navigation patterns",
      "Expo Audio for sound effects and guidance",
      "React Native Reanimated for smooth animations",
      "AsyncStorage for local data persistence"
    ]
  },
  // Professional projects (Live + Details only, no GitHub)
  {
    id: "hammr-physio",
    title: "Hammr Sports Physiotherapy",
    description: "Online physiotherapy clinic site with booking, service pages, and performance-focused Next.js build.",
    image: "/screenshots/hammr-physio-banner.png",
    categories: ["Professional", "Website"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React", "Framer Motion", "Vercel", "ESLint", "Prettier"],
    liveUrl: "https://hammrphysio.com/",
    detailedDescription: "Hammr Sports Physiotherapy is a comprehensive online physiotherapy platform founded by Namita Mehta, an Australian Titled Sports and Musculoskeletal Physiotherapist with over 16 years of experience. The website serves as a digital gateway for global patients seeking expert physiotherapy care from the comfort of their homes. Built with Next.js and modern web technologies, the platform showcases Namita's extensive credentials including her Double Master's from the University of South Australia-Adelaide and her work with elite athletes including cricketer Yuvraj Singh, actor Dev Patel, and various Australian national teams. The site features detailed service pages for sports injury rehabilitation and musculoskeletal physiotherapy, comprehensive booking functionality, and showcases her impressive portfolio of work with para-athletes and international sports teams. The platform emphasizes the benefits of virtual care including flexible scheduling, no waiting times, and consistent support between sessions.",
    keyFeatures: [
      "Global online physiotherapy consultations via Zoom/Facetime",
      "Comprehensive injury assessment and diagnosis services",
      "Sports injury rehabilitation programs",
      "Musculoskeletal physiotherapy treatments",
      "Flexible scheduling and booking system",
      "Professional credential showcase and portfolio",
      "Contact forms and WhatsApp integration",
      "Service pricing and package information"
    ],
    technicalHighlights: [
      "Next.js 14 with App Router for optimal performance",
      "TypeScript for type safety and maintainability",
      "Tailwind CSS for responsive design",
      "Image optimization with Next.js Image component",
      "SEO optimization for healthcare industry",
      "Mobile-first responsive design",
      "Fast loading times and performance optimization"
    ]
  },
  {
    id: "urban-world-consulting",
    title: "Urban World Consulting",
    description: "Corporate website for an urban strategy consulting firm with sector pages and media gallery.",
    image: "/screenshots/urban-world-consulting-banner.png",
    categories: ["Professional", "Website"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React", "Framer Motion", "Vercel", "ESLint", "Prettier"],
    liveUrl: "https://urbanworldco.in/",
    detailedDescription: "Urban World Consulting (OPC) Pvt. Ltd. is a Mumbai-based urban strategy consulting firm established by Mr. R.A. Rajeev, specializing in innovative solutions for sustainable urban development. The corporate website showcases the company's comprehensive approach to urban planning, emphasizing their unique philosophy of 'moving people, not cars.' Built with Next.js and modern web technologies, the platform presents UWC's extensive expertise across multiple sectors including urban mobility, urban design & development, environmental & public health engineering, and road infrastructure. The website features detailed service offerings spanning the entire project lifecycle from urban studies and strategic planning to technical design, engineering, and project management implementation support. The platform highlights UWC's commitment to creating equitable, well-connected communities through human-centered development strategies and includes multimedia content including founder interviews and project showcases.",
    keyFeatures: [
      "Comprehensive sector showcase (Urban Mobility, Design & Development, Environmental & Public Health, Road Infrastructure)",
      "Detailed service portfolio presentation",
      "Project lifecycle management information",
      "Founder director interview and company story",
      "Contact information and social media integration",
      "Media gallery and publications section",
      "Professional credential and expertise display",
      "Responsive design for all devices"
    ],
    technicalHighlights: [
      "Next.js 14 with App Router for optimal performance",
      "TypeScript for type safety and maintainability",
      "Tailwind CSS for responsive design",
      "Image optimization with Next.js Image component",
      "SEO optimization for consulting industry",
      "Video integration for founder interviews",
      "Mobile-first responsive design",
      "Fast loading times and performance optimization"
    ]
  },
  {
    id: "melo-works",
    title: "Melo Works",
    description: "Product site for creative studio tooling; minimal, fast, and SEO-optimized build.",
    image: "/screenshots/melo-works-banner.png",
    categories: ["Professional", "Website"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React", "Framer Motion", "Vercel", "ESLint", "Prettier"],
    liveUrl: "https://melo.works",
    detailedDescription: "Melo Works is India's first all-in-one digital music distribution service, revolutionizing how artists and labels distribute their music across global streaming platforms. Built with Next.js and modern web technologies, the platform offers comprehensive music distribution services including original music releases, cover song releases, promotional services, and subscription packages for labels. The website showcases Melo's extensive distribution network reaching audiences worldwide on major platforms like Spotify, Apple Music, YouTube Music, Amazon Music, and over 20 other streaming services. The platform emphasizes transparent royalty payments, artist-focused approach, and customized solutions for both individual artists and record labels. The site features detailed pricing information, artist success stories, and comprehensive guides on how to sell music online, making it accessible for musicians of all levels from emerging artists to established professionals.",
    keyFeatures: [
      "Global music distribution to 20+ streaming platforms",
      "Original music release services starting at ₹996",
      "Cover song release services with legal clearance",
      "Music promotion and marketing services",
      "Label subscription packages for unlimited releases",
      "Transparent royalty payments and tracking",
      "Artist dashboard and account management",
      "Comprehensive music business guides and resources"
    ],
    technicalHighlights: [
      "Next.js 14 with App Router for optimal performance",
      "TypeScript for type safety and maintainability",
      "Tailwind CSS for responsive design",
      "Image optimization with Next.js Image component",
      "SEO optimization for music industry",
      "Dynamic pricing display and service packages",
      "Mobile-first responsive design",
      "Fast loading times and performance optimization"
    ]
  },
  {
    id: "smaaash-entertainment",
    title: "Smaaash Entertainment",
    description: "High-traffic entertainment chain website with centers, activities, and booking CTAs.",
    image: "/screenshots/smaaash-entertainment-banner.png",
    categories: ["Professional", "Website"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React", "Framer Motion", "Vercel", "ESLint", "Prettier"],
    liveUrl: "https://smaaash-entertainment.in/",
    detailedDescription: "Smaaash Entertainment is India's premier entertainment chain offering cutting-edge gaming and entertainment experiences across multiple locations nationwide. Built with Next.js and modern web technologies, the website serves as the digital gateway for this high-traffic entertainment brand, showcasing their comprehensive range of activities including bowling, cricket simulators, virtual reality experiences, dance-off competitions, arcade games, and go-karting. The platform emphasizes their unique 'Play. Laugh. Bond' philosophy, creating immersive experiences that cater to every taste and age group. The website features detailed information about their multiple centers across India including Mumbai, Noida, Hyderabad, Ludhiana, Delhi, Gurugram, and other major cities. The platform includes comprehensive booking functionality, party and event services, corporate event packages, and special deals and combos, making it a one-stop destination for entertainment seekers looking for thrilling experiences and memorable moments.",
    keyFeatures: [
      "Comprehensive activity showcase (Bowling, Cricket, VR, Dance Off, Arcade, Go Karting)",
      "Multi-location center information and booking",
      "Party and event services for birthdays and corporate events",
      "Deals and combo packages for cost-effective entertainment",
      "Interactive booking system and contact forms",
      "Social media integration and community engagement",
      "Mobile-responsive design for on-the-go booking",
      "SEO optimization for entertainment industry"
    ],
    technicalHighlights: [
      "Next.js 14 with App Router for optimal performance",
      "TypeScript for type safety and maintainability",
      "Tailwind CSS for responsive design",
      "Image optimization with Next.js Image component",
      "SEO optimization for entertainment industry",
      "Dynamic content management for multiple locations",
      "Mobile-first responsive design",
      "Fast loading times and performance optimization"
    ]
  }
];